"""
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by
adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

limit = 4_000_000


def initial_solve(limit):
    result = 0

    a = 1
    b = 2

    while b < limit:
        result += b
        a, b = b, a + b
        a, b = b, a + b
        a, b = b, a + b

    return result


def improved_solve(limit):
    result = 0

    a = 1
    b = 2

    while b < limit:
        result += b
        a, b = a + 2 * b, 2 * a + 3 * b

    return result


def cheaty_solve(limit):
    result = 0

    a = 2
    PHI = 1.61803398874989484820

    while a < 4_000_000:
        result += a
        a = round(a * PHI ** 3)

    return result


# 4613732
print(initial_solve(limit))
print(improved_solve(limit))
print(cheaty_solve(limit))
